-- MySQL Script generated by MySQL Workbench
-- qui 20 fev 2025 07:32:14
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema banco_mercado
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema banco_mercado
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `banco_mercado` ;
USE `banco_mercado` ;

-- -----------------------------------------------------
-- Table `banco_mercado`.`tb_cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banco_mercado`.`tb_cliente` (
  `idcliente` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(80) NOT NULL,
  `cpf` VARCHAR(14) NOT NULL,
  `endereco` VARCHAR(100) NULL,
  PRIMARY KEY (`idcliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `banco_mercado`.`tb_produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banco_mercado`.`tb_produto` (
  `idproduto` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(120) NOT NULL,
  `tipo` VARCHAR(45) NOT NULL,
  `preco_compra` DECIMAL(10,2) NOT NULL,
  `preco_venda` DECIMAL(10,2) NULL,
  `margem_lucro` DECIMAL(10,2) NULL,
  `quantidade` DECIMAL(10,3) NOT NULL,
  PRIMARY KEY (`idproduto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `banco_mercado`.`tb_venda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banco_mercado`.`tb_venda` (
  `idvenda` INT NOT NULL AUTO_INCREMENT,
  `idcliente` INT NOT NULL,
  `idproduto` INT NOT NULL,
  `valor_total` DECIMAL(10,2) NULL,
  `data` DATE NULL,
  PRIMARY KEY (`idvenda`),
  INDEX `fk_tb_venda_tb_cliente_idx` (`idcliente` ASC) VISIBLE,
  INDEX `fk_tb_venda_tb_produto1_idx` (`idproduto` ASC) VISIBLE,
  CONSTRAINT `fk_tb_venda_tb_cliente`
    FOREIGN KEY (`idcliente`)
    REFERENCES `banco_mercado`.`tb_cliente` (`idcliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_venda_tb_produto1`
    FOREIGN KEY (`idproduto`)
    REFERENCES `banco_mercado`.`tb_produto` (`idproduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `banco_mercado`.`tb_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banco_mercado`.`tb_usuario` (
  `tb_usuario` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(80) NOT NULL,
  `email` VARCHAR(120) NOT NULL,
  `senha` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`tb_usuario`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;




INSERT INTO tb_cliente (nome, cpf, endereco) VALUES 
('Carlos Silva', '123.456.789-00', 'Rua das Flores, 123 - São Paulo, SP'),
('Ana Souza', '987.654.321-00', 'Av. Central, 456 - Rio de Janeiro, RJ'),
('Mariana Oliveira', '111.222.333-44', 'Rua Azul, 789 - Belo Horizonte, MG'),
('João Mendes', '555.666.777-88', 'Praça Verde, 321 - Curitiba, PR'),
('Fernanda Costa', '999.888.777-66', 'Av. Paulista, 1000 - São Paulo, SP'),
('Ricardo Santos', '222.333.444-55', 'Rua do Sol, 50 - Salvador, BA'),
('Beatriz Lima', '777.666.555-44', 'Rua da Praia, 200 - Recife, PE'),
('Eduardo Martins', '333.444.555-66', 'Av. Beira Rio, 80 - Porto Alegre, RS'),
('Patrícia Almeida', '666.777.888-99', 'Rua Nova, 10 - Fortaleza, CE'),
('Gustavo Rocha', '444.555.666-77', 'Av. das Árvores, 500 - Brasília, DF');

INSERT INTO tb_produto (nome, tipo, preco_compra, preco_venda, margem_lucro, quantidade) VALUES 
('Celular XYZ', 'Eletrônico', 1000.00, 1500.00, 50.00, 20),
('Notebook ABC', 'Eletrônico', 2500.00, 3500.00, 40.00, 15),
('Fone de Ouvido', 'Acessório', 100.00, 180.00, 80.00, 50),
('Teclado Mecânico', 'Periférico', 200.00, 350.00, 75.00, 30),
('Mouse Gamer', 'Periférico', 150.00, 250.00, 66.67, 40),
('Smartwatch', 'Eletrônico', 500.00, 750.00, 50.00, 25),
('Monitor Full HD', 'Eletrônico', 800.00, 1200.00, 50.00, 10),
('Cadeira Gamer', 'Mobiliário', 900.00, 1400.00, 55.56, 5),
('Impressora', 'Eletrônico', 600.00, 950.00, 58.33, 12),
('HD Externo 1TB', 'Armazenamento', 300.00, 500.00, 66.67, 20);

INSERT INTO tb_venda (idcliente, idproduto, valor_total, data) VALUES 
(1, 2, 3500.00, '2025-03-27'),
(3, 5, 250.00, '2025-03-26'),
(2, 1, 1500.00, '2025-03-25'),
(4, 7, 1200.00, '2025-03-24'),
(5, 3, 180.00, '2025-03-23'),
(6, 9, 950.00, '2025-03-22'),
(7, 4, 350.00, '2025-03-21'),
(8, 6, 750.00, '2025-03-20'),
(9, 10, 500.00, '2025-03-19'),
(10, 8, 1400.00, '2025-03-18');
